checkpoint: /home/ecm5702/scratch/aifs/checkpoint/5cfa2a40fa214167847fb1d9b5161812/inference-anemoi-by_epoch-epoch_1139-step_1854442.ckpt
debugging_info:
  config:
    dates:
      end: 2023-10-01
      frequency: 24
      start: 2023-08-01
    description: 5cfa2a40fa214167847fb1d9b5161812 - TC 2023 - 10 members - o96->o320
      - inference-anemoi-by_epoch-epoch_1139-step_1854442.ckpt
    ecflow:
      host: ecflow-gen-mlx-001
      limits:
        gpu: 10
      port: 3141
      target_running_user: mlx
    evaluation: false
    input:
      class: od
      grid: O96
      name: mars
      number: 6
      stream: eefo
      type: pf
    member_number: 6
    metadata:
      config_home: /home/ecm5702/prepml/ionc
      delete_before_running: false
      expver: ionc
      input: /home/ecm5702/dev/anemoi-inference/config/config_5cfa2a40fa214167847fb1d9b5161812_1139epochs_TC
      owner: ecm5702
      prepml_command: /usr/local/apps/prepml/0.99/env/bin/python3 -m prepml
      prepml_module_version: '0.99'
      run_number: 5
      time: '2025-04-24T16:24:35.119190'
    model:
      checkpoint: /home/ecm5702/scratch/aifs/checkpoint/5cfa2a40fa214167847fb1d9b5161812/inference-anemoi-by_epoch-epoch_1139-step_1854442.ckpt
      development_hacks:
        constant_high_res_forcings:
        - cos_latitude
        - cos_longitude
        - lsm
        - sin_latitude
        - sin_longitude
        - z
        constant_high_res_forcings_npz: /home/ecm5702/hpcperm/data/o320-forcings.npz
        extra_args:
          nsteps: 30
        high_res_input:
        - cos_julian_day
        - cos_latitude
        - cos_local_time
        - cos_longitude
        - insolation
        - lsm
        - sin_julian_day
        - sin_latitude
        - sin_local_time
        - sin_longitude
        - z
        output_template: /home/ecm5702/hpcperm/data/o320-template.grib
        time_step: 24h
      lead_time: 240h
      name: anemoi
      runner: downscaling
    output:
      class: rd
      database: marsrd
      name: fdb
      number: '6'
      stream: enfo
      type: pf
    platform:
      name: atos
    realtime: false
    runner:
      name: anemoi-dev
      venv: /hpcperm/ecm5702/.ds
      version: auto
  context: MemberInferenceContext
development_hacks:
  constant_high_res_forcings:
  - cos_latitude
  - cos_longitude
  - lsm
  - sin_latitude
  - sin_longitude
  - z
  constant_high_res_forcings_npz: /home/ecm5702/hpcperm/data/o320-forcings.npz
  extra_args:
    nsteps: 30
  high_res_input:
  - cos_julian_day
  - cos_latitude
  - cos_local_time
  - cos_longitude
  - insolation
  - lsm
  - sin_julian_day
  - sin_latitude
  - sin_local_time
  - sin_longitude
  - z
  output_template: /home/ecm5702/hpcperm/data/o320-template.grib
  time_step: 24h
input:
  grib:
    path: input.grib
lead_time: 240h
name: anemoi
output:
  grib:
    archive_requests:
      extra:
        database: marsrd
      path: archive.json
    check_encoding: true
    encoding:
      class: rd
      expver: ionc
      number: '6'
      stream: enfo
      type: pf
      typeOfGeneratingProcess: 4
    path: output-{levtype}-{class}-{type}-{stream}-{expver}-{date}-{time}.grib
report_error: true
runner: downscaling
write_initial_state: true