description: 920caa972da942f2987cde0f0a5426f0

dates:
  start: 2023-08-01
  end: 2023-09-01
  frequency: 24  # hours

ensemble:
  loop:
    number: 1/to/10

input:
  class: od
  stream: eefo
  type: pf
  number: "{number}"   
  # number: 2   # you can hard code this to initialise from 1 member
  grid: O96 

output:
  class: rd
  stream: enfo
  type: pf
  number: "{member_number}"
  # number: 2

runner:
  name: anemoi-dev
  venv: /home/ecm5702/dev/.ds-dyn

model:
  name: anemoi
  runner: downscaling
  checkpoint: /home/ecm5702/scratch/aifs/checkpoint/920caa972da942f2987cde0f0a5426f0/inference-anemoi-by_epoch-epoch_001-step_000112.ckpt
  development_hacks:
    time_step: 24h
    output_template: /home/ecm5702/hpcperm/data/o320-template.grib
    constant_high_res_forcings_npz: /home/ecm5702/hpcperm/data/o320-forcings.npz
    constant_high_res_forcings:  # order is not important
      - cos_latitude
      - cos_longitude
      - lsm
      - sin_latitude
      - sin_longitude
      - z
    high_res_input:  # same order as the input tensor !!!
      - cos_julian_day
      - cos_latitude
      - cos_local_time
      - cos_longitude
      - insolation
      - lsm
      - sin_julian_day
      - sin_latitude
      - sin_local_time
      - sin_longitude
      - z
      

evaluation: False

