description: e5f1790d9d26432db79e525f00ac0d32 - febr 2024 - 2 members - o96->o320 - inference-anemoi-by_time-epoch_257-step_594539.ckpt

dates:
  start: 2024-02-01
  end: 2024-03-01
  frequency: 24  # hours

ensemble:
  loop:
    number: 1/to/10

input:
  class: od
  stream: eefo
  type: pf
  number: "{number}"   
  # number: 2   # you can hard code this to initialise from 1 member
  grid: O96 

output:
  class: rd
  stream: enfo
  type: pf
  number: "{member_number}"
  # number: 2

runner:
  name: anemoi-dev
  venv: /hpcperm/ecm5702/.ds

model:
  name: anemoi
  runner: downscaling
  checkpoint: /home/ecm5702/scratch/aifs/checkpoint/e5f1790d9d26432db79e525f00ac0d32/inference-anemoi-by_time-epoch_257-step_594539.ckpt
  lead_time: 240h
  development_hacks:
    time_step: 24h
    output_template: /home/ecm5702/hpcperm/data/o320-template.grib
    constant_high_res_forcings_npz: /home/ecm5702/hpcperm/data/o320-forcings.npz
    constant_high_res_forcings:  # order is not important
      - cos_latitude
      - cos_longitude
      - lsm
      - sin_latitude
      - sin_longitude
      - z
    high_res_input:  # same order as the input tensor !!!
      - cos_julian_day
      - cos_latitude
      - cos_local_time
      - cos_longitude
      - insolation
      - lsm
      - sin_julian_day
      - sin_latitude
      - sin_local_time
      - sin_longitude
      - z

evaluation: False

