# This workflow runs pre-commit checks and pytest tests against multiple platforms and Python versions.
name: Code Quality and Testing

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
      - test/uv-pytest-workflow
  schedule:
    - cron: "9 2 * * 0" # at 9:02 on sunday

jobs:
  quality:
    uses: ecmwf/reusable-workflows/.github/workflows/qa-precommit-run.yml@v2
    with:
      skip-hooks: "no-commit-to-branch"

  checks:
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    uses: ecmwf/reusable-workflows/.github/workflows/qa-pytest-pyproject.yml@feat/uv-qa-pytest-pyproject
    with:
      python-version: ${{ matrix.python-version }}
